// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorShipBuilder.Data;

#nullable disable

namespace RazorShipBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416171553_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ssbuild")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorShipBuilder.Data.MountDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnergyDamage")
                        .HasColumnType("int");

                    b.Property<int>("EnergyShield")
                        .HasColumnType("int");

                    b.Property<bool>("IsContinualUse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("int");

                    b.Property<int>("PhysicalShield")
                        .HasColumnType("int");

                    b.Property<int>("PowerDraw")
                        .HasColumnType("int");

                    b.Property<int>("ReloadDuration")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresTurret")
                        .HasColumnType("bit");

                    b.Property<int>("TractorPower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MountDevices", "ssbuild");
                });

            modelBuilder.Entity("RazorShipBuilder.Data.MountPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsTurret")
                        .HasColumnType("bit");

                    b.Property<int?>("MountedDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StarshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MountedDeviceId");

                    b.HasIndex("StarshipId");

                    b.ToTable("MountPoints", "ssbuild");
                });

            modelBuilder.Entity("RazorShipBuilder.Data.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("GeneratorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaximumPower")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PowerGeneration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Starships", "ssbuild");
                });

            modelBuilder.Entity("RazorShipBuilder.Data.MountPoint", b =>
                {
                    b.HasOne("RazorShipBuilder.Data.MountDevice", "Device")
                        .WithMany()
                        .HasForeignKey("MountedDeviceId");

                    b.HasOne("RazorShipBuilder.Data.Starship", null)
                        .WithMany("MountPoints")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RazorShipBuilder.Data.Starship", b =>
                {
                    b.Navigation("MountPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
